server:
  port: 8089
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://iot-agent-database:5432/iot_agent}
    username: ${SPRING_DATASOURCE_USERNAME:gte}
    password: ${SPRING_DATASOURCE_PASSWORD:gte}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
jwt:
  secret: "${JWT_SECRET:supersecretkey}"
  expiration: 86400000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
