server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://iot-agent-database:5432/iot_agent
    username: gte
    password: gte
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
jwt:
  secret: "${JWT_SECRET:supersecretkey}"
  expiration: 86400000
